language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang

git:
  depth: 3

script:
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then mkdir build-openmp-on && (cd build-openmp-on && cmake -DUSE_OPENMP=ON .. && make -j4 && ./run-tests); fi
  - mkdir build-openmp-off && (cd build-openmp-off && cmake -DUSE_OPENMP=OFF .. && make -j4 && ./run-tests)

notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
    on_failure: always
