language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang

git:
  depth: 3

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update && sudo apt-get install -qq doxygen graphviz; fi

script:
  - ./.travis.sh

notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
    on_failure: always
