language: cpp

matrix:
  include:

    # build and run all tests on Linux with OpenMP enabled
    - os: linux
      dist: trusty
      compiler: gcc
      script:
         - mkdir build && cd build && cmake -DUSE_OPENMP=ON .. && make -j4 && make test

    # build and run all tests on Linux with OpenMP disabled
    - os: linux
      dist: trusty
      compiler: gcc
      script:
         - mkdir build && cd build && cmake -DUSE_OPENMP=OFF .. && make -j4 && make test

    # build the Doxygen-based documentation on Linux
    - os: linux
      dist: trusty
      compiler: gcc
      before_install:
        - sudo apt-get update && sudo apt-get install -qq doxygen graphviz
      script:
         - mkdir build && cd build && cmake .. && make doc

    # build and run all tests on OS X with OpenMP disabled
    - os: osx
      compiler: clang
      script:
         - mkdir build && cd build && cmake -DUSE_OPENMP=OFF .. && make -j4 && make test

    # build the Doxygen-based documentation on OS X
    - os: osx
      compiler: clang
      before_install:
        - brew install doxygen --with-graphviz
      script:
         - mkdir build && cd build && cmake -DUSE_OPENMP=OFF .. && make doc

git:
  depth: 3

notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
    on_failure: always
