name: Documentation generation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Doxygen
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install doxygen graphviz

    - name: Build documentation
      run: |
        mkdir build
        cd build
        cmake ..
        make doc

    - name: Generate artifact containing documentation
      run: tar -czvf docs.tar.gz build/html

    - name: Upload generated artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: docs.tar.gz
